- name: Retrieve sync server route
  shell: "oc get configmaps/{{ sync_secret_name }} -n {{ namespace }} -o jsonpath={.data.uri}"
  register: sync_server_uri_result

- set_fact:
    sync_server_uri: "{{ sync_server_uri_result.stdout }}"

- name: "Create sync server bind secret yaml file"
  template:
    src: bind_secret.yml
    dest: /tmp/bind-secret.yaml

- name: "Create binding secret"
  shell: "oc create -f /tmp/bind-secret.yaml -n {{ namespace }}"

- name: "Delete binding secret template file"
  file: path=/tmp/bind-secret.yaml state=absent

- name: Encode {{ CLIENT_ID }} credentials
  asb_encode_binding:
    fields:
      CLIENT_ID: "{{ CLIENT_ID }}"
  when: encode_asb_binding

- name: Populate {{ CLIENT_ID }} APB bind credentials
  set_fact:
    _apb_bind_creds: "{{ _apb_bind_creds|default({}) | combine( {item.name: item.value} ) }}"
  with_items:
    - { name: CLIENT_ID, value: '{{ CLIENT_ID }}' }
  when: not encode_asb_binding
  no_log: yes