- name: Give default user view permissions
  shell: 'oc policy add-role-to-user view system:serviceaccount:{{ namespace }}:{{ proxy_serviceaccount_name }} -n {{ namespace }}'

- name: "Create OAuth Proxy Serviceaccount yaml"
  template:
    src: oauth-proxy-sa.yml.j2
    dest: /tmp/oauth-proxy-sa.yaml

- name: "Create OAuth Proxy Serviceaccount"
  shell: "oc create -f /tmp/oauth-proxy-sa.yaml -n {{ namespace }}"

- include_tasks: provision-postgres.yml
- include_tasks: provision-sync-ui.yml
- include_tasks: provision-sync-server.yml

- include_role:
    name: oc-patch-file-to-configmap
  vars:
    file_contents: "{{ dashboard_file_contents }}"
    filename: "{{ dashboard_filename }}"
    configmap: "{{ dashboards_configmap }}"
    namespace: "{{ namespace }}"

# This is currently needed until https://github.com/openshift/ansible-service-broker/issues/847 is resolved
- name: "Make data availble for binding"
  asb_encode_binding:
    fields:
      namespace: "{{ namespace }}"
      sync_endpoint: "https://{{ data_sync_server_route.route.spec.host }}/graphql"
  when: encode_asb_binding