apiVersion: v1
kind: Secret
metadata:
  name: "{{ sync_secret_name }}-{{ CLIENT_ID }}"
  namespace: "{{ namespace }}"
  labels:
    mobile: enabled
    name: "{{ sync_secret_name }}-{{ CLIENT_ID }}"
    clientId: "{{ CLIENT_ID }}"
    serviceName: "{{ sync_secret_name }}"
stringData:
  clientId: "{{ CLIENT_ID }}"
  config: "{}"
  name: "{{ sync_secret_name }}"
  type: "{{ sync_secret_name }}"
  uri: "{{ sync_server_uri }}"
