- name: Delete {{ sync_secret_name }}-{{ _apb_bind_creds.clientId }} secret
  k8s_v1_secret:
    name: "{{ sync_secret_name }}-{{ _apb_bind_creds.clientId }}"
    namespace: "{{ namespace }}"
    state: absent